# Buster default python-3.7.3
FROM debian:buster
LABEL maintainer "Cheewai Lai <clai@csir.co.za>"
ARG DEBIAN_FRONTEND=noninteractive
ARG GOSU_VERSION=1.11
ARG DOCKERIZE_VERSION=v0.6.1
ARG http_proxy
ARG http_proxys

#ADD 71-apt-cacher-ng /etc/apt/apt.conf.d/71-apt-cacher-ng
RUN apt-get update \
 && apt-get -y upgrade \
 && apt-get -y install curl python3 python3-dev python3-pip build-essential \
 && curl -o /usr/local/bin/gosu -sSL "https://github.com/tianon/gosu/releases/download/${GOSU_VERSION}/gosu-amd64" \
 && chmod +x /usr/local/bin/gosu \
 && curl -k -fsSL https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz | tar xfz - -C /usr/bin \
 && pip3 install --upgrade pip \
 && pip3 install PyYAML \
 && pip3 install puka \
 && pip3 install gevent \
 && pip3 install gevent_inotifyx \
 && pip3 install rethinkdb \
 && pip3 install pyinotify \
 && pip3 install blinker raven --upgrade \
 && apt-get -y remove --purge python-dev build-essential \
 && apt-get -y autoremove && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
ADD docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod 755 /docker-entrypoint.sh \
 && chown root.root /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]
